xen: arm: fix build after libelf changes.
ed65808a8ed4 "libelf: check all pointer accesses" caused:
    kernel.c: In function 'kernel_elf_load':
    kernel.c:162:18: error: 'struct elf_binary' has no member named 'dest'
    make[4]: *** [kernel.o] Error 1

The field is now called dest_base. We also need to populate dest_size.

This fixes the build for me although have not tested it. I have a feeling that
loading the kernel from an ELF file on ARM doesn't currently work anyway
(everyone uses the zImage loader as far as I am aware).

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Reviewed-by: Andrew Cooper <andrew.cooper3@citrix.com>