libxc: xc_domain_resume_hvm is used by x86 only
The call site is enclosed by x86 define guards.

Without this patch:

[  334s] xc_resume.c:112:12: error: 'xc_domain_resume_hvm' defined but not used [-Werror=unused-function]
[  334s]  static int xc_domain_resume_hvm(xc_interface *xch, uint32_t domid)

Reported-by: Olaf Hering <olaf@aepfle.de>
Signed-off-by: Wei Liu <wei.liu2@citrix.com>